services:
  db:
    image: mongo:4.4
    container_name: zproject-mongo
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build:
      context: ./backend
    image: zproject-backend
    container_name: zproject-backend
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://db:27017/zproject
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_GRAPHQL_ENDPOINT: http://localhost:4000/graphql
    image: zproject-frontend
    container_name: zproject-frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local
    environment:
      - NEXT_PUBLIC_GRAPHQL_ENDPOINT=http://localhost:4000/graphql
    ports:
      - "3000:3000"

volumes:
  mongo-data:
